### ISSUE TITLE
lingo

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/gizra_slack_bot#8]
https://github.com/RoySegall/gizra_slack_bot/blob/master/src/NuntiusSuperCommand.php#L174-L176
https://github.com/RoySegall/gizra_slack_bot/tree/master/src/Plugins

**Comment by RachelBaram** [comment]
@RoySegall I proposed changes. I may have touched some parts that are not the actual text that users will see, so I hope it does not break anything. Cheers.

**Comment by RoySegall** [comment]
Thanks but I can't see a PR

**Comment by RachelBaram** [comment]
Yea, it didn't let me do a PR (or probably I couldn't figure out how to do it) but this did happen.
![roysegall_gizra_slack_bot](https://cloud.githubusercontent.com/assets/14312543/22286481/fc4b9460-e2f7-11e6-8cb2-bb6f1a57e412.png)

**Comment by RoySegall** [comment]
So this telling you can create PR from the PR from the UI. Click on the buttons and you'll get if from there.
